### ISSUE TITLE
`$(SRCROOT)` in `release_info_plist_path`

### ISSUE THREAD

**Issue by Vic-L** [jdee/settings-bundle#16]
Hihi, I have a problem executing this.

In this [line](https://github.com/jdee/settings-bundle/blob/master/lib/fastlane/plugin/settings_bundle/helper/settings_bundle_helper.rb#L75) of the `settings_bundle_helper.rb` file, the `release_info_plist_path` contains the `$(SRCROOT)` text in the file path, so it is throwing a `rb sysopen - file not found` error.

This fix made it work
`release_info_plist_path = File.join project_parent, release_info_plist_path.gsub("$(SRCROOT)/", "")`
but its definitely not right to do it this way.

Am I missing something to make it work?

Many thanks! I looking forward to using this gem it will help me greatly. Thanks for it!

**Comment by jdee** [comment]
@Vic-L Thanks for reporting this. This will require a patch. However, you can also work around it immediately by changing the setting in the project. Remove `$(SRCROOT)` and just specify the relative path in the project. Xcode should not care either way. (You can see how the examples in the repo are set up.) These are the same:

<img width="1408" alt="screen shot 2017-06-20 at 9 48 58 am" src="https://user-images.githubusercontent.com/121951/27345309-17bb3b7e-559e-11e7-8f9b-c8255ef44322.png">

<img width="1416" alt="screen shot 2017-06-20 at 9 49 13 am" src="https://user-images.githubusercontent.com/121951/27345319-186984cc-559e-11e7-834b-593e9837accd.png">

However, it's not unusual to have `$(SRCROOT)` in some of the settings. You could even substitute a user-defined setting there, like `$(MY_INFOPLIST_LOCATION)`. The plugin should be able to handle that. I should be able to get something out soon.

**Comment by Vic-L** [comment]
thanks that works. u r legend~

**Comment by jdee** [comment]
This wasn't very hard to fix. There is now a 1.2.1 that will support `$(SRCROOT)` and any other macros in the `INFOPLIST_FILE` setting.

Incidentally, other actions, particularly `commit_version_bump`, just substitute `.` for `$(SRCROOT)` and presumably won't support other macros.
