### ISSUE TITLE
Add other setting-options aswell 

### ISSUE THREAD

**Issue by EMart86** [jdee/settings-bundle#24]
I'd like to generate a whole settings bundle with your tool. Therefore i need to add other options aswell than just textual settings like entering a type (textual read/write, switch), a default value, a secure enter, ... 

Will this be available soon?

**Comment by jdee** [comment]
Hi @EMart86. The short answer is no, I wasn't planning on adding that support.

At a minimum, such an operation would have to:

1. Create a Settings.bundle directory.
2. Create one or more <locale>.lproj directory with a String.plist and add whatever you add to the settings bundle.
3. Create Root.plist or any other settings file (About.plist) and let you add any settings you like.

And as you say it requires support for types beyond title.

I have some ideas how to make this relatively easy, but they might require some internal Fastlane changes. (Which I'd like to make, but I need to discuss with the team first.)

Also, I'm curious about the use case. This seems like it would be helpful with template apps, but given Apple's recent shift on template apps, that's probably not very practical anymore.

**Comment by EMart86** [comment]
Hi @jdee, i know this sounds odd, but i'd have used it for adding only a couple of settings in the production app and the whole bunch of settings in the development app. Thus i'd be able to change all settings in the development version and only a bunch of settings in the production version.

I currently have a settings bundle for each environment and it's copied to the app by a run script. It's definatly not the nicest way to have the same settings for each environment and provide the translations for each setting in every environment and i'm still looking for any better solution but it did the trick for the meantime.

**Comment by jdee** [comment]
Hi @EMart86. For the time being (or indefinitely), you might consider the `remove_setting` plugin from @col, who had some similar use cases. https://github.com/col/fastlane-plugin-remove_setting
