### ISSUE TITLE
ignore_cocoapods_path has been removed from Fastlane

### ISSUE THREAD

**Issue by alpriest** [jdee/settings-bundle#25]
Since the inclusion of this [pull request](https://github.com/fastlane/fastlane/pull/14000) in Fastlane, the `Fastlane::Actions.ignore_cocoapods_path` has been removed in favour of `Fastlane::Helper::XcodeprojHelper` which detects Carthage and Cocoapod workspace project files.

My suggestion is that settings_bundle_helper.rb:143 needs changing to:
`xcodeproj_paths = Fastlane::Helper::XcodeprojHelper.find(all_xcodeproj_paths)`

And then the failing test in specs/settings_bundle_helper_spec.rb need their expectations changing to expect 2 calls to the Dir method.

**Comment by daniel-mohemian** [comment]
@jdee It would be really great if this could be merged.

The `settings-bundle` plugin is broken with Fastlane versions 2.113.0 and higher due to the change @alpriest linked above.

**Comment by alpriest** [comment]
I since found the fix I provided didn't quite work. I duplicated the original method into this codebase and I've got a fork available if you want to use that in the meantime.

https://github.com/alpriest/settings-bundle

**Comment by daniel-mohemian** [comment]
Cool, thanks for the heads up @alpriest!

We're currently using a fork which adapts the changes you made in #26 to make it work correctly. I submitted them as #27.

**Comment by jdee** [comment]
Fixed in 1.3.2.
