### ISSUE TITLE
New target param in 1.1 causes plug in to fail

### ISSUE THREAD

**Issue by stonedauwg** [jdee/settings-bundle#5]
The new target param added in the last release broke my update_settings_bundle fastlane plugin. Have already verified it works with 1.0 and fails after upgrading to 1.1. The issue is that the new param's key to fastlane is a duplicate of an existing key 'file':

```
FastlaneCore::ConfigItem.new(key: :file,
            env_name: "SETTINGS_BUNDLE_TARGET",
            description: "An optional target name from the project",
            optional: true,
            type: String)
```
I believe the key: should be key: :target instead of :file since :file is an existing param in 1.0

**Comment by jeff-jk** [comment]
+1

**Comment by jdee** [comment]
Thanks for reporting this. Obviously I could stand to test better. I've added some unit tests for the options that would have caught the problem.

And thanks for using the plugin. I hope it's been working well for you.

**Comment by jdee** [comment]
1.1.1 has been released with this fix.

**Comment by stonedauwg** [comment]
Works perfect now, thx
